### ISSUE TITLE
Clicking "New Game" while a game is in progress doubles seamus' move speed

### ISSUE THREAD

**Issue by chase-brenchley** [chase-brenchley/cuberoid#14]

**Comment by chase-brenchley** [comment]
Steps to reproduce:
1.  Start a new game
2. Press ESC to bring the menu up
3. Click on new game again
4. Notice the speedssssssss

**Comment by chase-brenchley** [comment]
Seems like now his movespeed doesn't increase but his jump height gets bigger

**Comment by Benjamin-Phillips** [comment]
Issue was that every time you hit new game the displayGame() function was calling game.init(), and game init calls requestAnimationFrame(gameLoop). So multiple game loops were being created, thus seamus' velocity (and everything else) was being updated multiple times per frame.
